### ISSUE TITLE
The accuracy is wrong

### ISSUE THREAD

**Issue by EririBigWin** [os-hxfan/Static_BFP_CNN#1]
I completed the instruction listed and "sh bfp_quant_resnet" but the accuracy is 0.0006, do you have any idea?

thanks

**Comment by os-hxfan** [comment]
Hi, thanks a lot for your attention on our repo!

To reproduce the issue you mentioned, I set up a new environment and run the "sh script/bfp_quant_resnet", here is the accuracy I can get:
![image](https://user-images.githubusercontent.com/50143823/104158797-02d48e00-53e6-11eb-9745-57af0b4c6592.png)

Are you sure the dataset you are using is correct?

I would like to suggest you to run the resnet without bfp_quant first.
To do this, set the "--bfp_quant" to 0 in the script.
You will get the accuracy like this:
![image](https://user-images.githubusercontent.com/50143823/104158960-6363cb00-53e6-11eb-97d7-9950ff1813f2.png)

In order to help you, pls send me the log you get by running the same.

**Comment by EririBigWin** [comment]
> Hi, thanks a lot for your attention on our repo!
> 
> To reproduce the issue you mentioned, I set up a new environment and run the "sh script/bfp_quant_resnet", here is the accuracy I can get:
> ![image](https://user-images.githubusercontent.com/50143823/104158797-02d48e00-53e6-11eb-9745-57af0b4c6592.png)
> 
> Are you sure the dataset you are using is correct?
> 
> I would like to suggest you to run the resnet without bfp_quant first.
> To do this, set the "--bfp_quant" to 0 in the script.
> You will get the accuracy like this:
> ![image](https://user-images.githubusercontent.com/50143823/104158960-6363cb00-53e6-11eb-97d7-9950ff1813f2.png)
> 
> In order to help you, pls send me the log you get by running the same.

Thanks a lot for your reply. I ran "create_corerain_valset.sh" and selected 5000 photos into 1000 folders named from 0 to 999. I guess I choose the wrong dataset but how can I change the dataset from "imagenet 50000" to "corerain 5000"?

Thank you.

**Comment by os-hxfan** [comment]
Hi,
I suggest you to use the original imagenet dataset.
To do this, pls do not process you datasert using  "create_corerain_valset.sh".
Just use the original imagenet and change the "--dataset_dir" in the script to the location where you save the whole dataset.
